[package]
name = "tir-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tir-core = { path = "../../core/" }
tir-macros = { path = "../../macros" }
thiserror = "1.0.59"
